name: Run Gender Agent

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'agent.py'
      - 'rules.py'
      - 'detectors/**'
      - 'requirements.txt'
      - 'sample_set.csv'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run agent
        run: |
          python agent.py --csv sample_set.csv --out sample_set_labeled.csv
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: labeled-csv
          path: sample_set_labeled.csv
